# Firework Algorithm for Optimization

- Autores originais: [*Ying Tan*](https://scholar.google.com/citations?user=PjNxSPsAAAAJ&hl=en) e [*Yuanchun Zhu*](https://ieeexplore.ieee.org/author/38008573100)
- Ano de Publicação: 2010
- Editora: [Springer](https://link.springer.com/chapter/10.1007/978-3-642-13495-1_44)
- Conferência: [Advances in Swarm Intelligence](https://link.springer.com/book/10.1007/978-3-642-13495-1): First International Conference, ICSI 2010, Beijing, China, June 12-15, 2010, Proceedings, Part I 1

## Descrição:
FA é um algoritmo de inteligência de enxames inspirado na explosão de fogos de artifício. Esse algoritmo é utilizado para a otimização global de funções complexas. São fornecidos dois processos de *“explosão”* (busca) e os mecanismos para manter a diversidade das *“faíscas”*.

In [60]:
import numpy as np
import pandas as pd
import random

In [ ]:
def objective_function(x):
    result = x**2
    return result

In [61]:
value = random.gauss(1,1)
value

2.0498718408786143

In [81]:
value = random.uniform(0,1)
value

0.3975802897608234

### Inicializando posições dos Fogos de Artifício:

In [63]:
def initialize_firework_locations(n, xmin, xmax):
    fireworks = xmin + (xmax - xmin) * np.random.rand(n)
    return fireworks

In [69]:
fireworks = initialize_firework_locations(5, -5.12, 5.12)
fireworks

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

### Calculando o número de faíscas:

In [76]:
def sparks_number(fx, m, ymax, eps=.00001):
    sum_difference_of_worst_fit_and_fx = np.sum(ymax-fx) + eps
    s = m* ymax - fx + eps/sum_difference_of_worst_fit_and_fx
    s = firework_boundaries(0.1, 0.8, m, s)
    return s

In [77]:
def firework_boundaries(a, b, m, s):
    term1 = round(a*m) * (s < (a*m))
    print(term1)
    term2 = round(b*m) * (s> b*m)
    print(term2)
    term3 = np.round(s) * (~(s < (a*m)) & ~((s > b *m) & (a<b<1)))
    print(term3)
    s_new = term1 + term2 + term3
    return s_new

In [75]:
x = np.array([45.2,5.2,12.5])
fx = objective_function(x)
m = 10
ymax = x.max()
sparks_number(fx, m, ymax)

[1 0 0]
[0 8 8]
[-0.  0.  0.]


array([1., 8., 8.])

### Obtendo localização das Faíscas:

In [ ]:
def explosion_amplitude(A_hat, fx, ymin, eps=.00001):
    sum_difference_of_fx_and_best_fit = np.sum(fx - ymin) + eps
    A = A_hat * (fx - ymin + eps/ sum_difference_of_fx_and_best_fit)
    return A

In [86]:
d = 6
round(6 * random.uniform(0,1))

1

In [ ]:
def obtain_location_of_spark(d):
    #selecting z dimensions to be affected
    xj = np.zeros(d)
    z = round(d * random.uniform(0,1))
    random_dimensions = np.random.choice(d, z, replace=False)
    for i in random_dimensions:
        
    random_affected = np.where

In [94]:
np.random.choice(10, 10, replace=False)

array([2, 7, 5, 6, 0, 3, 4, 8, 1, 9])

### Mantendo faíscas no espaço de busca: 

In [ ]:
def round_sparks_number(S, a, b, m):
    si = np.zeros(s.shape)
    for i in range(len(s)):
        if S[i] > a*m:
           si[i] = round(a*m)
        elif S[i] > a*b:
           si[i] = round(b * m)
        else:
            si[i] = round(s[i])

        if S[i] > si[i]:
            S[i] = si[i]
    return S

### Amplitude das Explosões:

In [ ]:
def explosion_amplitude(A, fx, ymin, sum_of_difference, eps =.00001):
    Ai = A * (fx - ymin + eps/sum_of_difference + eps)
    return Ai

### Gerando faíscas:

In [ ]:
def affected_directions(d):
    z = round(d * random.rand(0,1))
    return z

In [ ]:
def spark_location(Ai, xi, d):
    r

In [ ]:
x = np.array([.08, 3.2, 1.0, 3.1, 0.01, 2.2])
#n_sparks = sparks_number(x, m, eps) 
m = 50
s = sparks_number(x, m)
a = 0.8
b = 0.04
S = sparks_number(x, m)
print(S)
S = round_sparks_number(S, a, b, m)
print(S)